name: luna_assistant
description: "A voice assistant powered by Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  file_picker: ^6.1.1
  flutter_tts: ^3.8.5
  excel: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  process_run: ^0.13.0
  url_launcher: ^6.2.1
  http: ^0.13.6
  avatar_glow: ^2.0.2
  google_sign_in: ^6.1.6  
  flutter_sound: ^9.1.6
  animations: ^2.0.7
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

plugin:
  platforms:
    android:
      package: com.example.luna_assistant
      pluginClass: LunaAssistantPlugin
      fileName: luna_assistant.dart
    ios:
      pluginClass: LunaAssistantPlugin
      fileName: luna_assistant.dart
    web:
      pluginClass: LunaAssistantWeb
      fileName: luna_assistant.dart
    macos:
      pluginClass: LunaAssistantMacOS
      fileName: luna_assistant.dart
    windows:
      pluginClass: LunaAssistantWindows
      fileName: luna_assistant.dart
    linux:
      pluginClass: LunaAssistantLinux
      fileName: luna_assistant.dart
